# app/db/project_repository.py

from sqlalchemy.orm import Session
from typing import List, Optional
from app.db.models import Project, ProjectFile, Message, Task, AuditLogEntry  # Added ORM models
from app.agents.base import VirtualLabState  # Added Pydantic domain model
from app.schemas.project import ConversationMessage, TaskItem, AuditEntry  # Added Pydantic schemas

import logging
logger = logging.getLogger(__name__)

class ProjectRepository:
    """
    Encapsulates all database access logic for the Project and related tables.
    Adheres to the Repository Pattern, ensuring the Service Layer is unaware of
    database specifics (like SQLAlchemy, ORMs, or SQL).
    """
    
    def __init__(self, db_session: Session):
        """
        The DB session is injected into the repository instance.
        """
        self.db = db_session
        
    def create_project_and_files(self, project: Project, files: List[ProjectFile]) -> Project:
        """
        Persists the new Project and all associated ProjectFile records 
        in a single, atomic transaction.
        
        Args:
            project: The new Project model instance.
            files: A list of new ProjectFile model instances.
            
        Returns:
            The committed Project instance.
        """
        try:
            # 1. Add the main project record
            self.db.add(project)
            
            # 2. Add all file records
            for file in files:
                self.db.add(file)
            
            # 3. Commit the transaction (atomicity guaranteed here)
            self.db.commit()
            
            # 4. Refresh the project to ensure we have any defaults generated by the DB
            self.db.refresh(project)
            
            return project
            
        except Exception as e:
            # CRITICAL: Rollback the entire transaction on failure
            self.db.rollback()
            # Re-raise the exception for the Service Layer to handle (e.g., clean up files)
            raise e
    
    def get_project_state(self, project_id: str) -> VirtualLabState:
        """
        Reconstructs the complete VirtualLabState from database.
        
        This method encapsulates ALL database access and ORM → Pydantic conversion logic.
        The calling layer (Worker) doesn't need to know about SQLAlchemy models or conversion.
        
        Args:
            project_id: The project ID to fetch state for
            
        Returns:
            A complete VirtualLabState object reconstructed from database
            
        Raises:
            ValueError: If project not found
        """
        # 1. Fetch Project (master record)
        project = self.db.query(Project).filter(Project.project_id == project_id).first()
        if not project:
            raise ValueError(f"Project {project_id} not found in database")
        
        # 2. Fetch and convert Messages (ORM → Pydantic)
        message_records = self.db.query(Message).filter(
            Message.project_id == project_id
        ).order_by(Message.created_at).all()
        messages = [
            ConversationMessage(role=msg.role, content=msg.content)
            for msg in message_records
        ]
        
        # 3. Fetch and convert Tasks (ORM → Pydantic)
        task_records = self.db.query(Task).filter(
            Task.project_id == project_id
        ).order_by(Task.created_at).all()
        task_list = [
            TaskItem(
                id=task.task_id,
                description=task.description,
                status=task.status,
                result=task.result
            )
            for task in task_records
        ]
        
        # 4. Fetch and convert Audit Log (ORM → Pydantic)
        audit_records = self.db.query(AuditLogEntry).filter(
            AuditLogEntry.project_id == project_id
        ).order_by(AuditLogEntry.timestamp).all()
        audit_log = [
            AuditEntry(
                timestamp=entry.timestamp.isoformat(),
                agent=entry.agent,
                action=entry.action,
                current_phase=entry.current_phase,
                details=entry.details or {}
            )
            for entry in audit_records
        ]
        
        # 5. Reconstruct VirtualLabState (scratchpad could be stored in Project later)
        return VirtualLabState(
            messages=messages,
            task_list=task_list,
            scratchpad={},  # TODO: Could load from Project.scratchpad if we store it
            next_agent=project.next_agent or "pi_agent",
            audit_log=audit_log,
            current_phase=project.current_phase
        )
            
    # FUTURE METHODS (Just for context, not needed for Feature 1 POST)
    
    # def get_project_by_id(self, project_id: str) -> Optional[Project]:
    #     """Fetches a project by its ID."""
    #     return self.db.query(Project).filter(Project.project_id == project_id).first()
    
    # def update_project_state(self, project_id: str, current_phase: str, next_agent: str):
    #     """Updates the phase and next agent fields."""
    #     # ... implementation ...
    #     pass

    def get_project_with_state(self, project_id: str, owner_id: str) -> dict:
        """
        Retrieves a project with its complete state, validating ownership.

        This is specifically for the GET /projects/{id} endpoint.
        Returns all project data including files, messages, tasks, and audit log.

        Args:
            project_id: The project ID to retrieve
            owner_id: The user ID requesting access (for ownership validation)

        Returns:
            Dictionary containing all project data ready for API response

        Raises:
            ValueError: If project not found or user doesn't own it
        """
        # 1. Fetch the project with ownership validation
        project = self.db.query(Project).filter(
            Project.project_id == project_id
        ).first()

        if not project:
            raise ValueError(f"Project {project_id} not found")

        if project.owner_id != owner_id:
            raise ValueError(f"User {owner_id} does not have access to project {project_id}")

        # 2. Fetch related data (Messages)
        message_records = self.db.query(Message).filter(
            Message.project_id == project_id
        ).order_by(Message.created_at).all()
        messages = [
            ConversationMessage(role=msg.role, content=msg.content)
            for msg in message_records
        ]

        # 3. Fetch Tasks
        task_records = self.db.query(Task).filter(
            Task.project_id == project_id
        ).order_by(Task.created_at).all()
        task_list = [
            TaskItem(
                id=task.agent_task_id,  # Use agent_task_id, not task_id
                description=task.description,
                status=task.status,
                result=task.result
            )
            for task in task_records
        ]

        # 4. Fetch Audit Log
        audit_records = self.db.query(AuditLogEntry).filter(
            AuditLogEntry.project_id == project_id
        ).order_by(AuditLogEntry.timestamp).all()
        audit_log = [
            AuditEntry(
                timestamp=entry.timestamp,
                agent=entry.agent,
                action=entry.action,
                current_phase=entry.current_phase,
                details=entry.details or {}
            )
            for entry in audit_records
        ]

        # 5. Fetch Files
        files = project.files  # Uses SQLAlchemy relationship

        # 6. Construct response dictionary
        return {
            "project_id": project.project_id,
            "original_research_goal": project.original_research_goal,
            "refined_research_goal": project.refined_research_goal,
            "messages": messages,
            "task_list": task_list,
            "scratchpad": {},  # TODO: Load from project if we store it later
            "next_agent": project.next_agent or "pi_agent",
            "audit_log": audit_log,
            "current_phase": project.current_phase,
            "files": files  # ORM objects will be converted by Pydantic
        }

    def save_agent_results(self, project_id: str, final_state: VirtualLabState) -> None:
        """
        Persists the agent's final state back to the database.
        
        This method handles the Pydantic → ORM conversion and ensures
        all related tables are updated atomically.
        
        Args:
            project_id: The project ID
            final_state: The VirtualLabState returned by the agent
            
        Raises:
            ValueError: If project not found
        """
        try:
            # 1. Fetch the project record AND Update Project fields (Keep this at the top)
            project = self.db.query(Project).filter(Project.project_id == project_id).first()
            if not project:
                raise ValueError(f"Project {project_id} not found")
            project.refined_research_goal = final_state.scratchpad.get('refined_research_goal')
            project.current_phase = final_state.current_phase
            project.next_agent = final_state.next_agent
            
            # --- TASK PERSISTENCE (ROBUST ID-BASED CHECK) ---
            
            # 2. Get existing agent IDs for this project
            existing_agent_task_ids = {
                task_id[0] for task_id in self.db.query(Task.agent_task_id).filter(
                    Task.project_id == project_id
                ).all()
            }
            
            # 3. Insert NEW tasks (if ID doesn't exist)
            new_tasks_added = 0
            for task in final_state.task_list:
                if task.id not in existing_agent_task_ids:
                    self.db.add(Task(
                        project_id=project_id,
                        agent_task_id=task.id,  # Use the new column!
                        description=task.description,
                        status=task.status,
                        result=task.result
                    ))
                    new_tasks_added += 1
            
            # --- MESSAGE AND AUDIT PERSISTENCE (SLICING IS ACCEPTABLE HERE) ---

            # 4. Add NEW messages (Slicing is fine for append-only lists like messages/audit)
            existing_message_count = self.db.query(Message).filter(Message.project_id == project_id).count()
            new_messages = final_state.messages[existing_message_count:]
            for msg in new_messages:
                self.db.add(Message(project_id=project_id, role=msg.role, content=msg.content))
            
            # 5. Add NEW audit entries
            existing_audit_count = self.db.query(AuditLogEntry).filter(AuditLogEntry.project_id == project_id).count()
            new_audit_entries = final_state.audit_log[existing_audit_count:]
            for entry in new_audit_entries:
                self.db.add(AuditLogEntry(
                    project_id=project_id, timestamp=entry.timestamp, agent=entry.agent,
                    action=entry.action, current_phase=entry.current_phase, details=entry.details
                ))

            # 6. Commit all changes atomically
            self.db.commit()
            
            logger.info(
                f"Agent results saved to database",
                extra={
                    "project_id": project_id,
                    "messages_added": len(new_messages),
                    "tasks_added": new_tasks_added,
                    "audit_entries_added": len(new_audit_entries),
                    "refined_goal": project.refined_research_goal[:100] if project.refined_research_goal else None
                }
            )
            
        except Exception as e:
            logger.error(
                f"Failed to save agent results",
                extra={"project_id": project_id, "error": str(e)},
                exc_info=True
            )
            self.db.rollback()
            raise